---
- name: Create Traefik configuration directories on host
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ config_dir }}/traefik"
    - "{{ config_dir }}/traefik/dynamic"

- name: Create Traefik static configuration
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ config_dir }}/traefik/traefik.yml"
    mode: '0644'

- name: Create Traefik dynamic configuration for services
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: "{{ config_dir }}/traefik/dynamic/dynamic.yml"
    mode: '0644'

- name: Create acme.json for Let's Encrypt certificates
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik/acme.json"
    state: touch
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Create Traefik Docker Compose file
  ansible.builtin.template:
    src: traefik-compose.yml.j2
    dest: "{{ base_dir }}/traefik-compose.yml"
    mode: '0644'

- name: Start Traefik service using Docker Compose
  ansible.builtin.shell: |
    cd {{ base_dir }}
    docker compose -f traefik-compose.yml up -d
  register: traefik_deploy
  changed_when: traefik_deploy.rc == 0
