---
- name: Configure UFW firewall
  when: firewall_enabled
  block:
    - name: Reset UFW to defaults
      community.general.ufw:
        state: reset

    - name: Set UFW default policies
      community.general.ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Allow HTTP
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: Allow service ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "{{ services.mattermost.port }}"
        - "{{ services.jenkins.port }}"

    - name: Enable UFW
      community.general.ufw:
        state: enabled

- name: Configure fail2ban
  when: fail2ban_enabled
  block:
    - name: Create fail2ban jail for SSH
      ansible.builtin.copy:
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 3

          [sshd]
          enabled = true
          port = ssh
          logpath = /var/log/auth.log
          backend = %(sshd_backend)s
        dest: /etc/fail2ban/jail.local
        mode: '0644'

    - name: Start and enable fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: true

- name: Configure automatic updates
  when: auto_updates_enabled
  block:
    - name: Configure unattended upgrades
      ansible.builtin.copy:
        content: |
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id}:${distro_codename}-security";
              "${distro_id}ESMApps:${distro_codename}-apps-security";
              "${distro_id}ESM:${distro_codename}-infra-security";
          };
          Unattended-Upgrade::AutoFixInterruptedDpkg "true";
          Unattended-Upgrade::MinimalSteps "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Automatic-Reboot "false";
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: '0644'

    - name: Enable automatic updates
      ansible.builtin.copy:
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "7";
          APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: '0644'
